🚧 Create Infer container (#318)

diff --git a/github-bot/Dockerfile b/github-bot/Dockerfile
--- a/github-bot/Dockerfile
+++ b/github-bot/Dockerfile
@@ -3,8 +3,80 @@
 FROM curlimages/curl AS downloader
 ARG RUN_JAVA_VERSION=1.3.8
 RUN curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /tmp/run-java.sh
+RUN 
+# Disable sandboxing
+# Without this opam fails to compile OCaml for some reason. We don't need sandboxing inside a Docker container anyway.
+RUN opam init --reinit --bare --disable-sandboxing --yes --auto-setup
 
+# Download the latest Infer from git
+RUN cd / && \
+  git clone --depth 1 https://github.com/facebook/infer/
 
+# Build opam deps first, then infer. This way if any step fails we
+# don't lose the significant amount of work done in the previous
+# steps.
+RUN cd /infer && ./build-infer.sh java --only-setup-opam
+RUN cd /infer && ./build-infer.sh java
+# Install infer
+ENV PATH /infer/bin:${PATH}
+# Generate a release
+RUN cd /infer && \
+  make install-with-libs \
+  BUILD_MODE=opt \
+  PATCHELF=patchelf \
+  DESTDIR="/infer-release" \
+  libdir_relative_to_bindir="../lib"
+ENV GRADLE_VERSION 7.6.
+RUN set -o errexit -o nounset \
+  && echo "Downloading Gradle" \
+  && wget --no-verbose --output-document=gradle.zip "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" \
+  \
+  && echo "Installing Gradle" \
+  && unzip gradle.zip \
+  && rm gradle.zip \
+  && mv "gradle-${GRADLE_VERSION}" "${GRADLE_HOME}/" \
+  && ln --symbolic "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle \
+  \
+  && echo "Testing Gradle installation" \
+  && gradle --version
+
+# Set Gradle in the environment variables
+ENV GRADLE_HOME /opt/gradle-4.5.1
+ENV PATH $PATH:/opt/gradle-4.5.1/bin
+# Get the infer release
+COPY --from=compilator /infer-release/usr/local /infer
+
+# Downloading and installing Maven
+# 1- Define a constant with the version of maven you want to install
+ARG MAVEN_VERSION=3.6.1         
+
+# 2- Define a constant with the working directory
+ARG USER_HOME_DIR="/root"
+
+# 3- Define the SHA key to validate the maven download
+ARG SHA=b4880fb7a3d81edd190a029440cdf17f308621af68475a4fe976296e71ff4a4b546dd6d8a58aaafba334d309cc11e638c52808a4b0e818fc0fd544226d952544
+
+# 4- Define the URL where maven can be downloaded from
+ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
+
+# 5- Create the directories, download maven, validate the download, install it, remove downloaded file and set links
+RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
+  && echo "Downlaoding maven" \
+  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
+  \
+  && echo "Checking download hash" \
+  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
+  \
+  && echo "Unziping maven" \
+  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
+  \
+  && echo "Cleaning and setting links" \
+  && rm -f /tmp/apache-maven.tar.gz \
+  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
+
+# 6- Define environmental variables required by Maven, like Maven_Home directory and where the maven repo is located
+ENV MAVEN_HOME /usr/share/maven
+ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
 # FROM eclipse-temurin:11-jdk-alpine
 FROM eclipse-temurin:19-jdk-alpine
 
